# Generated by Django 5.2 on 2025-04-08 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resposta",
            name="alternativa_escolhida",
        ),
        migrations.RemoveField(
            model_name="resposta",
            name="prova_atribuida",
        ),
        migrations.AddField(
            model_name="resposta",
            name="alternativa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="provas.alternativa",
            ),
        ),
        migrations.AddField(
            model_name="resposta",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
