# Generated by Django 5.2 on 2025-04-05 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvaParticipante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respondida", models.BooleanField(default=False)),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prova",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="provas.prova"
                    ),
                ),
            ],
            options={
                "unique_together": {("prova", "participante")},
            },
        ),
        migrations.AlterField(
            model_name="resposta",
            name="prova_atribuida",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="provas.provaparticipante",
            ),
        ),
        migrations.DeleteModel(
            name="ProvaAtribuida",
        ),
    ]
