# Generated by Django 5.2 on 2025-04-06 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provas", "0002_provaparticipante_alter_resposta_prova_atribuida_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prova",
            name="participantes",
            field=models.ManyToManyField(
                related_name="provas_designadas", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
