# Generated by Django 5.2 on 2025-04-06 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provas", "0003_prova_participantes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="provaparticipante",
            name="participante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
